import type { PageSourceBundle } from '../types'

export const pageSources: Record<string, PageSourceBundle> = {
  collection: {
    pageId: 'collection',
    title: '收藏追蹤來源',
    entries: [
      {
        id: 'collection-cycleapple',
        name: 'ffxiv-collection-tc (cycleapple)',
        url: 'https://cycleapple.github.io/ffxiv-collection-tc/',
        category: 'inspiration',
        note: '收藏追蹤頁的分類方式、狀態切換與本機追蹤流程參考來源。',
      },
      {
        id: 'collection-custom-deliveries',
        name: 'Custom Deliveries - Console Games Wiki',
        url: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
        category: 'data',
        note: '老主顧 NPC 與解鎖資訊的整理來源。2026-03-05 查閱時已更新到 Nitowikwe。',
      },
      {
        id: 'collection-allied-societies',
        name: 'Allied Society Quests - Console Games Wiki',
        url: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
        category: 'data',
        note: '友好部落清單、版本與解鎖脈絡來源。2026-03-05 查閱時已更新到 Yok Huy。',
      },
      {
        id: 'collection-soktai',
        name: 'Soktai FFXIV Tools',
        url: 'https://soktai.ca/ffxiv/allied-society-quests',
        category: 'data',
        note: '友好部落任務整理與交叉比對來源。',
      },
    ],
  },
  craft: {
    pageId: 'craft',
    title: '製作助手來源',
    entries: [
      {
        id: 'craft-bestcraft-repo',
        name: 'Tnze / ffxiv-best-craft',
        url: 'https://github.com/Tnze/ffxiv-best-craft',
        category: 'inspiration',
        note: '製作工作流、模擬方向與 solver 類型的主要參考來源。本站重新整理 UI、文案與資料流程。',
      },
      {
        id: 'craft-xivapi-docs',
        name: 'XIVAPI Docs',
        url: 'https://v2.xivapi.com/docs',
        category: 'data',
        note: '配方搜尋與自動帶入使用的官方 API 文件來源。',
      },
      {
        id: 'craft-bestcraft-license',
        name: 'BestCraft License (AGPL-3.0)',
        url: 'https://github.com/Tnze/ffxiv-best-craft/blob/master/LICENSE',
        category: 'data',
        note: 'BestCraft 原始專案授權資訊來源。',
      },
    ],
  },
  tools: {
    pageId: 'tools',
    title: '工具箱來源',
    entries: [
      {
        id: 'tools-collection-ref',
        name: 'ffxiv-collection-tc (cycleapple)',
        url: 'https://cycleapple.github.io/ffxiv-collection-tc/',
        category: 'inspiration',
        note: '收藏追蹤工具參考來源。',
      },
      {
        id: 'tools-bestcraft-ref',
        name: 'FFXIV Best Craft',
        url: 'https://github.com/Tnze/ffxiv-best-craft',
        category: 'inspiration',
        note: '製作模擬與 solver 類型工具參考來源。',
      },
      {
        id: 'tools-market-ref',
        name: 'FFXIV Market (beherw)',
        url: 'https://beherw.github.io/FFXIV_Market/',
        category: 'inspiration',
        note: '查價工作流、OCR 與批次整理流程參考來源。',
      },
      {
        id: 'tools-treasure-ref',
        name: 'xiv-tc-treasure-finder (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/',
        category: 'inspiration',
        note: '藏寶圖點位、組隊與路線規劃流程參考來源。',
      },
      {
        id: 'tools-toolbox-ref',
        name: 'xiv-tc-toolbox (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
        category: 'inspiration',
        note: '整體工具箱資訊架構與功能分類參考來源。',
      },
      {
        id: 'tools-xivapi',
        name: 'XIVAPI Docs',
        url: 'https://v2.xivapi.com/docs',
        category: 'data',
        note: '站內多數公共資料查詢使用的官方 API 文件來源。',
      },
    ],
  },
  goldSaucer: {
    pageId: 'goldSaucer',
    title: '金碟來源',
    entries: [
      {
        id: 'gold-wiki',
        name: 'Console Games Wiki: Gold Saucer Active Time Events',
        url: 'https://ffxiv.consolegameswiki.com/wiki/Gold_Saucer_Active_Time_Events',
        category: 'data',
        note: 'GATE 時段規則與活動資料參考來源。',
      },
      {
        id: 'gold-toolbox',
        name: 'xiv-tc-toolbox (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
        category: 'inspiration',
        note: '金碟工具在地化與資訊排列方式的參考來源。',
      },
    ],
  },
  market: {
    pageId: 'market',
    title: '查價來源',
    entries: [
      {
        id: 'market-ref-beherw',
        name: 'FFXIV Market (beherw)',
        url: 'https://beherw.github.io/FFXIV_Market/',
        category: 'inspiration',
        note: 'OCR 匯入、批次表格與最近更新摘要的工作流參考來源。',
      },
      {
        id: 'market-tesseract',
        name: 'Tesseract.js',
        url: 'https://github.com/naptha/tesseract.js',
        category: 'data',
        note: '站內截圖 OCR 功能使用的開源辨識套件來源。',
      },
    ],
  },
  treasure: {
    pageId: 'treasure',
    title: '藏寶圖來源',
    entries: [
      {
        id: 'treasure-ref-cycleapple',
        name: 'xiv-tc-treasure-finder (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/',
        category: 'inspiration',
        note: '藏寶圖單人 / 8 人流程、組隊操作與路線規劃主要參考來源。',
      },
      {
        id: 'treasure-ref-toolbox',
        name: 'xiv-tc-toolbox (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
        category: 'inspiration',
        note: '工具箱層級的功能分類與補充參考來源。',
      },
      {
        id: 'treasure-data-cycleapple',
        name: 'cycleapple treasure data.js',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/js/data.js',
        category: 'data',
        note: '藏寶圖點位 snapshot 的上游資料來源。',
      },
      {
        id: 'treasure-firebase-ref',
        name: 'cycleapple firebase-config.js',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/js/party/firebase-config.js',
        category: 'data',
        note: '即時組隊功能使用 Firebase 的參考來源。',
      },
      {
        id: 'treasure-xivapi',
        name: 'XIVAPI',
        url: 'https://xivapi.com/',
        category: 'data',
        note: '地圖資料與公開表單查詢參考來源。',
      },
      {
        id: 'treasure-coords',
        name: 'XIVAPI MapCoordinates.md',
        url: 'https://github.com/xivapi/ffxiv-datamining/blob/master/docs/MapCoordinates.md',
        category: 'data',
        note: '地圖座標換算規則參考來源。',
      },
    ],
  },
}
