import type { PageSourceBundle } from '../types'

export const pageSources: Record<string, PageSourceBundle> = {
  collection: {
    pageId: 'collection',
    title: '收藏追蹤來源',
    entries: [
      {
        id: 'collection-cycleapple',
        name: 'ffxiv-collection-tc (cycleapple)',
        url: 'https://cycleapple.github.io/ffxiv-collection-tc/',
        category: 'inspiration',
        note: '收藏清單、篩選與追蹤流程參考來源之一；本站改寫成適合本專案的清單管理介面。',
      },
      {
        id: 'collection-custom-deliveries',
        name: 'Custom Deliveries - Console Games Wiki',
        url: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
        category: 'data',
        note: '老主顧名單、解鎖條件與獎勵摘要的主要公開資料來源。',
      },
      {
        id: 'collection-allied-societies',
        name: 'Allied Society Quests - Console Games Wiki',
        url: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
        category: 'data',
        note: '友好部落名單、分類與支援職能的主要公開資料來源。',
      },
      {
        id: 'collection-soktai',
        name: 'Soktai FFXIV Tools',
        url: 'https://soktai.ca/ffxiv/allied-society-quests',
        category: 'data',
        note: '友好部落整理方式與任務檢索體驗的補充參考來源。',
      },
    ],
  },
  craft: {
    pageId: 'craft',
    title: '製作助手來源',
    entries: [
      {
        id: 'craft-bestcraft-repo',
        name: 'Tnze / ffxiv-best-craft',
        url: 'https://github.com/Tnze/ffxiv-best-craft',
        category: 'inspiration',
        note: '製作工作台、技能面板、solver 思路與操作節奏的主要參考來源；本站改為 React 版站內工具。',
      },
      {
        id: 'craft-bestcraft-zh-tw',
        name: 'BestCraft zh-TW locale',
        url: 'https://github.com/Tnze/ffxiv-best-craft/tree/master/src/assets/locales',
        category: 'data',
        note: '技能名稱以 BestCraft 的繁體中文語系為對照依據，避免自行亂翻。',
      },
      {
        id: 'craft-xivapi-docs',
        name: 'XIVAPI Docs',
        url: 'https://v2.xivapi.com/docs',
        category: 'data',
        note: '配方搜尋與資料帶入所使用的公開 API 文件。',
      },
      {
        id: 'craft-bestcraft-license',
        name: 'BestCraft License (AGPL-3.0)',
        url: 'https://github.com/Tnze/ffxiv-best-craft/blob/master/LICENSE',
        category: 'data',
        note: 'BestCraft 原始專案授權條款來源。',
      },
    ],
  },
  tools: {
    pageId: 'tools',
    title: '工具箱來源',
    entries: [
      {
        id: 'tools-collection-ref',
        name: 'ffxiv-collection-tc (cycleapple)',
        url: 'https://cycleapple.github.io/ffxiv-collection-tc/',
        category: 'inspiration',
        note: '收藏追蹤與工具箱分頁規劃的參考來源。',
      },
      {
        id: 'tools-bestcraft-ref',
        name: 'FFXIV Best Craft',
        url: 'https://github.com/Tnze/ffxiv-best-craft',
        category: 'inspiration',
        note: '製作模擬與技能序列設計的重要參考來源。',
      },
      {
        id: 'tools-market-ref',
        name: 'FFXIV Market (beherw)',
        url: 'https://beherw.github.io/FFXIV_Market/',
        category: 'inspiration',
        note: '查價流程、OCR 匯入與工作表節奏的參考來源。',
      },
      {
        id: 'tools-treasure-ref',
        name: 'xiv-tc-treasure-finder (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/',
        category: 'inspiration',
        note: '藏寶圖點位檢視、隊伍協作與房間流程的參考來源。',
      },
      {
        id: 'tools-toolbox-ref',
        name: 'xiv-tc-toolbox (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
        category: 'inspiration',
        note: '整站工具整理方向與中文工具箱體驗的參考來源。',
      },
      {
        id: 'tools-xivapi',
        name: 'XIVAPI Docs',
        url: 'https://v2.xivapi.com/docs',
        category: 'data',
        note: '站內多項資料查詢功能使用的公開 API 文件。',
      },
    ],
  },
  goldSaucer: {
    pageId: 'goldSaucer',
    title: '金碟遊樂場來源',
    entries: [
      {
        id: 'gold-wiki',
        name: 'Console Games Wiki: Gold Saucer Active Time Events',
        url: 'https://ffxiv.consolegameswiki.com/wiki/Gold_Saucer_Active_Time_Events',
        category: 'data',
        note: 'GATE 時段規則與活動列表的參考資料來源。',
      },
      {
        id: 'gold-toolbox',
        name: 'xiv-tc-toolbox (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
        category: 'inspiration',
        note: '中文工具頁呈現方式與金碟輔助功能的參考來源。',
      },
    ],
  },
  market: {
    pageId: 'market',
    title: '查價工具來源',
    entries: [
      {
        id: 'market-ref-beherw',
        name: 'FFXIV Market (beherw)',
        url: 'https://beherw.github.io/FFXIV_Market/',
        category: 'inspiration',
        note: 'OCR 匯入、搜尋中心、單品市場面板與最近更新工作流的主要參考來源。',
      },
      {
        id: 'market-universalis',
        name: 'Universalis API',
        url: 'https://universalis.app/',
        category: 'data',
        note: '單品市場資料、批次比價與最近更新物品清單的主要資料來源。',
      },
      {
        id: 'market-xivapi',
        name: 'XIVAPI Docs',
        url: 'https://v2.xivapi.com/docs',
        category: 'data',
        note: '道具名稱補完、配方搜尋與道具詳情補查所使用的公開 API 文件。',
      },
      {
        id: 'market-tesseract',
        name: 'Tesseract.js',
        url: 'https://github.com/naptha/tesseract.js',
        category: 'data',
        note: '站內 OCR 功能使用的開源辨識庫。',
      },
    ],
  },
  treasure: {
    pageId: 'treasure',
    title: '藏寶圖來源',
    entries: [
      {
        id: 'treasure-ref-cycleapple',
        name: 'xiv-tc-treasure-finder (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/',
        category: 'inspiration',
        note: '單人 / 8 人分流、地圖點位與房間協作流程的主要參考來源。',
      },
      {
        id: 'treasure-ref-toolbox',
        name: 'xiv-tc-toolbox (cycleapple)',
        url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
        category: 'inspiration',
        note: 'FF14 中文工具箱整合方向與互動節奏的參考來源。',
      },
      {
        id: 'treasure-data-cycleapple',
        name: 'cycleapple treasure data.js',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/js/data.js',
        category: 'data',
        note: '藏寶圖點位資料整理的上游參考來源；本站已改為本地快照方式使用。',
      },
      {
        id: 'treasure-firebase-ref',
        name: 'cycleapple firebase-config.js',
        url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/js/party/firebase-config.js',
        category: 'data',
        note: '多人即時同步房間功能的 Firebase 設計參考來源。',
      },
      {
        id: 'treasure-xivapi',
        name: 'XIVAPI',
        url: 'https://xivapi.com/',
        category: 'data',
        note: '地圖與道具相關資料的公開 API 來源。',
      },
      {
        id: 'treasure-coords',
        name: 'XIVAPI MapCoordinates.md',
        url: 'https://github.com/xivapi/ffxiv-datamining/blob/master/docs/MapCoordinates.md',
        category: 'data',
        note: '地圖座標換算規則的技術參考來源。',
      },
    ],
  },
}
