import type { ToolDirectoryEntry } from '../types'

export const toolDirectory: ToolDirectoryEntry[] = [
  {
    id: 'universalis',
    name: 'Universalis',
    category: '市場查價',
    description: '提供市場板價格、成交與上架資訊，是站內查價功能的主要資料來源。',
    url: 'https://universalis.app/',
    futureIntegration: true,
  },
  {
    id: 'teamcraft',
    name: 'FFXIV Teamcraft',
    category: '製作與清單',
    description: '大型整合型工具站，適合作為未來功能分區與工作流設計的參考。',
    url: 'https://ffxivteamcraft.com/',
    futureIntegration: false,
  },
  {
    id: 'garland-tools',
    name: 'Garland Tools',
    category: '資料庫 / 任務',
    description: '適合當作資料查詢與工具整合的參考來源，尤其是導航與資料密度。',
    url: 'https://garlandtools.org/',
    futureIntegration: true,
  },
  {
    id: 'xivapi',
    name: 'XIVAPI',
    category: '資料 API',
    description: '提供資料搜尋與後續站內資料工具的 API 基礎。',
    url: 'https://v2.xivapi.com/docs',
    futureIntegration: true,
  },
  {
    id: 'market-reference',
    name: 'FFXIV Market (beherw)',
    category: '查價參考',
    description: '站內查價頁的體驗、資訊重點與操作流程參考來源之一。',
    url: 'https://beherw.github.io/FFXIV_Market/',
    futureIntegration: true,
  },
  {
    id: 'toolbox-reference',
    name: 'xiv-tc-toolbox (cycleapple)',
    category: '工具箱參考',
    description: '金碟與藏寶圖工具的功能切分與方向參考來源之一。',
    url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
    futureIntegration: true,
  },
  {
    id: 'gate-reference',
    name: 'Gold Saucer Active Time Events',
    category: '金碟時段',
    description: 'GATE 時段規則與活動描述的公開參考資料。',
    url: 'https://ffxiv.consolegameswiki.com/wiki/Gold_Saucer_Active_Time_Events',
    futureIntegration: true,
  },
]
