import type { ToolDirectoryEntry } from '../types'

export const toolDirectory: ToolDirectoryEntry[] = [
  {
    id: 'collection-tc',
    name: '收藏追蹤 / collection-tc 站內版',
    category: '站內工具 / 收藏追蹤',
    description: '整合老主顧與友好部落的收藏追蹤流程，狀態與願望清單只保存在瀏覽器。',
    url: 'https://cycleapple.github.io/ffxiv-collection-tc/',
    internalPath: '#/collection',
    integrationStatus: 'partial',
  },
  {
    id: 'bestcraft',
    name: '製作助手 / BestCraft 站內版',
    category: '站內工具 / 製作模擬',
    description: '站內化的製作模擬、配方帶入、macro 匯入匯出與 solver 工作流。',
    url: 'https://github.com/Tnze/ffxiv-best-craft',
    internalPath: '#/craft',
    integrationStatus: 'partial',
    licenseNote: 'AGPL-3.0',
  },
  {
    id: 'market-reference',
    name: 'FFXIV Market (beherw)',
    category: '查價工具參考',
    description: 'OCR 匯入、批次工作表與最近更新摘要的參考來源。',
    url: 'https://beherw.github.io/FFXIV_Market/',
    integrationStatus: 'reference',
  },
  {
    id: 'treasure-finder-reference',
    name: 'xiv-tc-treasure-finder (cycleapple)',
    category: '藏寶圖 / 路線規劃參考',
    description: '藏寶圖點位、隊伍房間與路線規劃的重要參考來源。',
    url: 'https://cycleapple.github.io/xiv-tc-treasure-finder/',
    integrationStatus: 'reference',
  },
  {
    id: 'toolbox-reference',
    name: 'xiv-tc-toolbox (cycleapple)',
    category: '工具箱參考',
    description: 'FF14 多功能工具箱的資訊架構與功能分類參考來源。',
    url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
    integrationStatus: 'reference',
  },
  {
    id: 'teamcraft',
    name: 'FFXIV Teamcraft',
    category: '製作 / 清單管理',
    description: '製作、採集、清單管理與流程規劃的常用外部工具。',
    url: 'https://ffxivteamcraft.com/',
    integrationStatus: 'external',
  },
  {
    id: 'garland-tools',
    name: 'Garland Tools',
    category: '資料庫',
    description: 'FF14 道具、採集與任務資料的經典資料庫。',
    url: 'https://garlandtools.org/',
    integrationStatus: 'external',
  },
  {
    id: 'xivapi',
    name: 'XIVAPI Docs',
    category: '資料 API',
    description: '站內多個資料查詢功能使用的官方 API 文件。',
    url: 'https://v2.xivapi.com/docs',
    integrationStatus: 'reference',
  },
  {
    id: 'gate-reference',
    name: 'Gold Saucer Active Time Events',
    category: '金碟參考',
    description: 'GATE 時段與活動規則的資料來源。',
    url: 'https://ffxiv.consolegameswiki.com/wiki/Gold_Saucer_Active_Time_Events',
    integrationStatus: 'reference',
  },
]
