import type { ToolDirectoryEntry } from '../types'

export const toolDirectory: ToolDirectoryEntry[] = [
  {
    id: 'universalis',
    name: 'Universalis',
    category: '市場查價',
    description: '國際市場資料站。本站目前不直接拿它做繁中服價格，但仍值得當作外部參考。',
    url: 'https://universalis.app/',
    futureIntegration: true,
  },
  {
    id: 'teamcraft',
    name: 'FFXIV Teamcraft',
    category: '製作與清單',
    description: '大型製作與採集管理工具，適合當作未來站內工作流整合的參考。',
    url: 'https://ffxivteamcraft.com/',
    futureIntegration: false,
  },
  {
    id: 'garland-tools',
    name: 'Garland Tools',
    category: '資料庫',
    description: '道具與任務資料整理完整，適合作為站內查詢功能的架構靈感。',
    url: 'https://garlandtools.org/',
    futureIntegration: true,
  },
  {
    id: 'xivapi',
    name: 'XIVAPI',
    category: '資料 API',
    description: '公開 API 與文件，適合用來支撐站內查詢、圖片與資料整理。',
    url: 'https://v2.xivapi.com/docs',
    futureIntegration: true,
  },
  {
    id: 'market-reference',
    name: 'FFXIV Market (beherw)',
    category: '繁中服比價',
    description: '本站雙服比價頁的主要參考來源，已改用本站自己的多項目工作表重做。',
    url: 'https://beherw.github.io/FFXIV_Market/',
    futureIntegration: true,
  },
  {
    id: 'toolbox-reference',
    name: 'xiv-tc-toolbox (cycleapple)',
    category: '繁中工具箱',
    description: '金碟與藏寶圖等小工具的方向參考來源，本站會挑合適功能站內化。',
    url: 'https://cycleapple.github.io/xiv-tc-toolbox/',
    futureIntegration: true,
  },
  {
    id: 'gate-reference',
    name: 'Gold Saucer Active Time Events',
    category: '金碟時程',
    description: 'GATE 時段規則的主要參考來源。本站另加上僅供參考的活動預測。',
    url: 'https://ffxiv.consolegameswiki.com/wiki/Gold_Saucer_Active_Time_Events',
    futureIntegration: true,
  },
]
