import type { CollectionCategoryId, CollectionEntry, CollectionExpansionId, CollectionSupportRole } from '../types'

export const collectionCategories: Array<{ id: CollectionCategoryId; label: string }> = [
  { id: 'custom-deliveries', label: '老主顧' },
  { id: 'allied-societies', label: '友好部落' },
]

export const collectionExpansions: Array<{ id: CollectionExpansionId; label: string }> = [
  { id: 'arr', label: '2.x 重生之境' },
  { id: 'hw', label: '3.x 蒼穹之禁城' },
  { id: 'sb', label: '4.x 紅蓮之狂潮' },
  { id: 'shb', label: '5.x 漆黑的反叛者' },
  { id: 'ew', label: '6.x 曉月之終途' },
  { id: 'dt', label: '7.x 黃金的遺產' },
]

export const collectionSupportRoles: Array<{ id: CollectionSupportRole; label: string }> = [
  { id: 'crafting', label: '製作' },
  { id: 'gathering', label: '採集' },
  { id: 'fishing', label: '釣魚' },
  { id: 'combat', label: '戰鬥' },
]

export const collectionEntries: CollectionEntry[] = [
  {
    id: 'zhloe',
    name: 'Zhloe Aliapoh',
    category: 'custom-deliveries',
    expansion: 'hw',
    patch: '3.55',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'Idyllshire',
    unlockQuest: 'Go West, Craftsman',
    unlockSummary: '老主顧系統起點。完成前置後即可開始每週交貨。',
    rewardSummary: ['製作 / 採集白票', '經驗值', '滿意度提升'],
    notes: '每週有交件上限，建議當作所有老主顧流程的起點。',
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'mnaago',
    name: "M'naago",
    category: 'custom-deliveries',
    expansion: 'sb',
    patch: '4.3',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: "Rhalgr's Reach",
    unlockQuest: "None Forgotten, None Forsaken",
    unlockSummary: '紅蓮版本老主顧之一，適合中後期白票與經驗值累積。',
    rewardSummary: ['製作 / 採集白票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'kurenai',
    name: 'Kurenai',
    category: 'custom-deliveries',
    expansion: 'sb',
    patch: '4.4',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'The Ruby Sea',
    unlockQuest: 'The Seaweed Is Always Greener',
    unlockSummary: '需要先完成對應支線，之後可穩定提供每週交件。',
    rewardSummary: ['製作 / 採集白票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'adonkiragh',
    name: 'Adkiragh',
    category: 'custom-deliveries',
    expansion: 'shb',
    patch: '5.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'Eulmore',
    unlockQuest: 'Oh, Beehive Yourself',
    unlockSummary: '漆黑版本老主顧之一，適合白票與角色經驗補充。',
    rewardSummary: ['製作 / 採集白票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'kai-shirr',
    name: 'Kai-Shirr',
    category: 'custom-deliveries',
    expansion: 'shb',
    patch: '5.3',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'Eulmore',
    unlockQuest: 'The Boutique Always Wins',
    unlockSummary: '和 Eulmore 劇情關聯較深的老主顧。',
    rewardSummary: ['製作 / 採集白票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'ehll-tou',
    name: 'Ehll Tou',
    category: 'custom-deliveries',
    expansion: 'shb',
    patch: '5.5',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'The Firmament',
    unlockQuest: 'If Songs Had Wings',
    unlockSummary: '和伊修加德重建流程有關，適合順路一起做。',
    rewardSummary: ['製作 / 採集白票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'charlemend',
    name: 'Charlemend',
    category: 'custom-deliveries',
    expansion: 'ew',
    patch: '6.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'The Firmament',
    unlockQuest: 'The Better Half',
    unlockSummary: '曉月版本追加的老主顧之一。',
    rewardSummary: ['製作 / 採集白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'ameliance',
    name: 'Ameliance',
    category: 'custom-deliveries',
    expansion: 'ew',
    patch: '6.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'Old Sharlayan',
    unlockQuest: 'Of Mothers and Merchants',
    unlockSummary: '曉月版本老主顧之一，和薩雷安支線整合度高。',
    rewardSummary: ['製作 / 採集白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'andexio',
    name: 'Anden',
    category: 'custom-deliveries',
    expansion: 'ew',
    patch: '6.55',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'Il Mheg',
    unlockQuest: 'That\'s So Anden',
    unlockSummary: '6.x 後段開放的老主顧，交件節奏與其他老主顧相同。',
    rewardSummary: ['製作 / 採集白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'margrat',
    name: 'Margrat',
    category: 'custom-deliveries',
    expansion: 'dt',
    patch: '7.05',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'Tuliyollal',
    unlockQuest: 'A Request of One\'s Own',
    unlockSummary: '7.x 老主顧起點之一，適合黃金版本日常整理。',
    rewardSummary: ['製作 / 採集白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'nitowikwe',
    name: 'Nitowikwe',
    category: 'custom-deliveries',
    expansion: 'dt',
    patch: '7.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: 'Tuliyollal',
    unlockQuest: 'A Labor of Leaf and Loam',
    unlockSummary: '黃金版本追加老主顧，可和其他 7.x 內容一起排每週清單。',
    rewardSummary: ['製作 / 採集白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'amaljaa',
    name: "Amalj'aa",
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: 'Southern Thanalan',
    unlockQuest: 'Peace for Thanalan',
    unlockSummary: '2.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '軍票', '坐騎 / 雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'sylphs',
    name: 'Sylphs',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: 'East Shroud',
    unlockQuest: 'Seeking Solace',
    unlockSummary: '2.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '軍票', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'kobolds',
    name: 'Kobolds',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: 'Outer La Noscea',
    unlockQuest: 'Highway Robbery',
    unlockSummary: '2.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '軍票', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'sahagin',
    name: 'Sahagin',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: 'Western La Noscea',
    unlockQuest: 'They Came from the Deep',
    unlockSummary: '2.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '軍票', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'ixal',
    name: 'Ixal',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.35',
    supportRoles: ['crafting'],
    location: 'North Shroud',
    unlockQuest: 'A Bad Bladder',
    unlockSummary: '2.x 製作型友好部落，適合 DoH 職業練等。',
    rewardSummary: ['製作經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'vanu-vanu',
    name: 'Vanu Vanu',
    category: 'allied-societies',
    expansion: 'hw',
    patch: '3.0',
    supportRoles: ['combat'],
    location: 'The Sea of Clouds',
    unlockQuest: 'Three Beaks to the Wind',
    unlockSummary: '3.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '坐騎', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'gnath',
    name: 'Gnath',
    category: 'allied-societies',
    expansion: 'hw',
    patch: '3.2',
    supportRoles: ['combat'],
    location: 'The Dravanian Forelands',
    unlockQuest: 'A Difference of Opinion',
    unlockSummary: '3.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'moogles',
    name: 'Moogles',
    category: 'allied-societies',
    expansion: 'hw',
    patch: '3.3',
    supportRoles: ['crafting'],
    location: 'The Churning Mists',
    unlockQuest: 'Tricks and Stones',
    unlockSummary: '3.x 製作型友好部落，適合 DoH 每日任務。',
    rewardSummary: ['製作經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'kojin',
    name: 'Kojin',
    category: 'allied-societies',
    expansion: 'sb',
    patch: '4.0',
    supportRoles: ['combat'],
    location: 'The Ruby Sea',
    unlockQuest: 'Heaven-sent',
    unlockSummary: '4.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '雜貨', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'ananta',
    name: 'Ananta',
    category: 'allied-societies',
    expansion: 'sb',
    patch: '4.0',
    supportRoles: ['combat'],
    location: 'The Fringes',
    unlockQuest: 'Brooding Broodmother',
    unlockSummary: '4.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'namazu',
    name: 'Namazu',
    category: 'allied-societies',
    expansion: 'sb',
    patch: '4.3',
    supportRoles: ['crafting', 'gathering'],
    location: 'The Azim Steppe',
    unlockQuest: 'Something Fishy This Way Comes',
    unlockSummary: '4.x 製作 / 採集型友好部落，適合 DoH 與 DoL 練等。',
    rewardSummary: ['製作 / 採集經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'pixies',
    name: 'Pixies',
    category: 'allied-societies',
    expansion: 'shb',
    patch: '5.1',
    supportRoles: ['combat'],
    location: 'Il Mheg',
    unlockQuest: 'Manic Pixie Dream Realm',
    unlockSummary: '5.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'qitari',
    name: 'Qitari',
    category: 'allied-societies',
    expansion: 'shb',
    patch: '5.2',
    supportRoles: ['gathering'],
    location: 'The Rak\'tika Greatwood',
    unlockQuest: 'The Stewards of Note',
    unlockSummary: '5.x 採集型友好部落。',
    rewardSummary: ['採集經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'dwarves',
    name: 'Dwarves',
    category: 'allied-societies',
    expansion: 'shb',
    patch: '5.3',
    supportRoles: ['crafting'],
    location: 'Kholusia',
    unlockQuest: 'It\'s Dwarfin\' Time',
    unlockSummary: '5.x 製作型友好部落。',
    rewardSummary: ['製作經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'arkasodara',
    name: 'Arkasodara',
    category: 'allied-societies',
    expansion: 'ew',
    patch: '6.15',
    supportRoles: ['combat'],
    location: 'Thavnair',
    unlockQuest: 'Hippos Born to Run',
    unlockSummary: '6.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '坐騎', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'omicrons',
    name: 'Omicrons',
    category: 'allied-societies',
    expansion: 'ew',
    patch: '6.25',
    supportRoles: ['gathering'],
    location: 'Ultima Thule',
    unlockQuest: 'Where No Loporrit Has Gone Before',
    unlockSummary: '6.x 採集型友好部落。',
    rewardSummary: ['採集經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'loporrits',
    name: 'Loporrits',
    category: 'allied-societies',
    expansion: 'ew',
    patch: '6.35',
    supportRoles: ['crafting'],
    location: 'Mare Lamentorum',
    unlockQuest: 'A Dream Worth Chasing',
    unlockSummary: '6.x 製作型友好部落。',
    rewardSummary: ['製作經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'pelupelu',
    name: 'Pelupelu',
    category: 'allied-societies',
    expansion: 'dt',
    patch: '7.15',
    supportRoles: ['combat'],
    location: 'Urqopacha',
    unlockQuest: 'The Feat of Gold',
    unlockSummary: '7.x 戰鬥型友好部落。',
    rewardSummary: ['部落聲望', '雜貨', '外觀獎勵'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'mamool-ja',
    name: 'Mamool Ja',
    category: 'allied-societies',
    expansion: 'dt',
    patch: '7.25',
    supportRoles: ['gathering'],
    location: 'Yak T\'el',
    unlockQuest: 'Aiming High',
    unlockSummary: '7.x 採集型友好部落。',
    rewardSummary: ['採集經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'yok-huy',
    name: 'Yok Huy',
    category: 'allied-societies',
    expansion: 'dt',
    patch: '7.35',
    supportRoles: ['crafting'],
    location: 'Kozama\'uka',
    unlockQuest: 'A Work of Giants',
    unlockSummary: '7.x 製作型友好部落。',
    rewardSummary: ['製作經驗', '部落聲望', '雜貨'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
]

export function getCollectionEntryById(entryId: string): CollectionEntry | undefined {
  return collectionEntries.find((entry) => entry.id === entryId)
}
