import type { CollectionCategoryId, CollectionEntry, CollectionExpansionId, CollectionSupportRole } from '../types'

export const collectionCategories: Array<{ id: CollectionCategoryId; label: string }> = [
  { id: 'custom-deliveries', label: '老主顧' },
  { id: 'allied-societies', label: '友好部落' },
]

export const collectionExpansions: Array<{ id: CollectionExpansionId; label: string }> = [
  { id: 'arr', label: '2.x 新生' },
  { id: 'hw', label: '3.x 蒼天' },
  { id: 'sb', label: '4.x 紅蓮' },
  { id: 'shb', label: '5.x 漆黑' },
  { id: 'ew', label: '6.x 曉月' },
  { id: 'dt', label: '7.x 黃金' },
]

export const collectionSupportRoles: Array<{ id: CollectionSupportRole; label: string }> = [
  { id: 'crafting', label: '製作' },
  { id: 'gathering', label: '採集' },
  { id: 'fishing', label: '釣魚' },
  { id: 'combat', label: '戰鬥' },
]

export const collectionEntries: CollectionEntry[] = [
  {
    id: 'zhloe',
    name: '庫洛依・阿里阿波',
    category: 'custom-deliveries',
    expansion: 'hw',
    patch: '3.55',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '伊修加德 / 田園郡',
    unlockQuest: '一流工匠的新工具',
    unlockSummary: '完成莫古力蠻族與蒼天主線後開放第一位老主顧。',
    rewardSummary: ['白票', '經驗值', '好感度劇情'],
    notes: '老主顧每週 12 張交貨券，每位 NPC 上限 6 張。',
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'mnaago',
    name: '梅娜歌',
    category: 'custom-deliveries',
    expansion: 'sb',
    patch: '4.3',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '拉札罕 / 神拳痕',
    unlockQuest: '梅娜歌的老主顧',
    unlockSummary: '完成紅蓮支線後可解鎖。',
    rewardSummary: ['白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'kurenai',
    name: '紅玉',
    category: 'custom-deliveries',
    expansion: 'sb',
    patch: '4.4',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '紅玉海 / 碧甲羅',
    unlockQuest: '海底的新朋友',
    unlockSummary: '適合紅蓮後期票券與劇情追蹤。',
    rewardSummary: ['白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'adonkiragh',
    name: '阿朵奇拉',
    category: 'custom-deliveries',
    expansion: 'shb',
    patch: '5.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '優雷卡歐斯 / 艾爾摩亞',
    unlockQuest: '天使與誓言',
    unlockSummary: '漆黑版本起可用紫票與白票同步培養。',
    rewardSummary: ['白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'kai-shirr',
    name: '凱西爾',
    category: 'custom-deliveries',
    expansion: 'shb',
    patch: '5.3',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '水晶都',
    unlockQuest: '來自水晶都的委託',
    unlockSummary: '漆黑主城常用老主顧。',
    rewardSummary: ['白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'ehll-tou',
    name: '艾爾圖',
    category: 'custom-deliveries',
    expansion: 'shb',
    patch: '5.5',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '伊修加德重建區',
    unlockQuest: '幼龍的交貨委託',
    unlockSummary: '和重建區成長線相連。',
    rewardSummary: ['白票', '紫票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'charlemend',
    name: '夏雷蒙',
    category: 'custom-deliveries',
    expansion: 'ew',
    patch: '6.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '伊修加德 / 神殿騎士團',
    unlockQuest: '貴族的老主顧',
    unlockSummary: '曉月初期的老主顧之一。',
    rewardSummary: ['白票', '紫票', '橙票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'ameliance',
    name: '阿梅莉安絲',
    category: 'custom-deliveries',
    expansion: 'ew',
    patch: '6.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '舊薩雷安',
    unlockQuest: '母親的委託',
    unlockSummary: '曉月版本的高人氣老主顧。',
    rewardSummary: ['白票', '紫票', '橙票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'andexio',
    name: '安德克修',
    category: 'custom-deliveries',
    expansion: 'ew',
    patch: '6.55',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '十三世界 / 虛無界',
    unlockQuest: '與虛無之友交易',
    unlockSummary: '曉月後段新增老主顧。',
    rewardSummary: ['白票', '紫票', '橙票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'margrat',
    name: '瑪格拉特',
    category: 'custom-deliveries',
    expansion: 'dt',
    patch: '7.05',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '圖拉爾',
    unlockQuest: '黃金鄉的老主顧',
    unlockSummary: '7.0 系列首位黃金老主顧。',
    rewardSummary: ['白票', '紫票', '橙票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'nitowikwe',
    name: '尼托維凱',
    category: 'custom-deliveries',
    expansion: 'dt',
    patch: '7.15',
    supportRoles: ['crafting', 'gathering', 'fishing'],
    location: '圖拉爾',
    unlockQuest: '獵人的請託',
    unlockSummary: '截至 2026-03-05 的最新黃金老主顧。',
    rewardSummary: ['白票', '紫票', '橙票', '經驗值'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Custom_Deliveries',
  },
  {
    id: 'amaljaa',
    name: '亞馬爾迦',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: '南薩納蘭',
    unlockQuest: '友誼的火種',
    unlockSummary: '新生戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '寵物'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'sylphs',
    name: '希爾芙',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: '東黑衣森林',
    unlockQuest: '小小綠人',
    unlockSummary: '新生戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '表情'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'kobolds',
    name: '柯博德',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: '外拉諾西亞',
    unlockQuest: '熾熱之爐',
    unlockSummary: '新生戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '家具'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'sahagin',
    name: '薩哈金',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.x',
    supportRoles: ['combat'],
    location: '西拉諾西亞',
    unlockQuest: '潮汐之友',
    unlockSummary: '新生戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '寵物'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'ixal',
    name: '伊克薩爾',
    category: 'allied-societies',
    expansion: 'arr',
    patch: '2.35',
    supportRoles: ['crafting'],
    location: '北黑衣森林',
    unlockQuest: '修復雲端營地',
    unlockSummary: '新生唯一製作部落，對 DoH 很重要。',
    rewardSummary: ['製作經驗', '聲望', '坐騎'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'vanu-vanu',
    name: '瓦努瓦努',
    category: 'allied-societies',
    expansion: 'hw',
    patch: '3.0',
    supportRoles: ['combat'],
    location: '阿巴拉提亞雲海',
    unlockQuest: '雲海之民',
    unlockSummary: '蒼天戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '家具'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'gnath',
    name: '骨頜族',
    category: 'allied-societies',
    expansion: 'hw',
    patch: '3.2',
    supportRoles: ['combat'],
    location: '龍堡參天高地',
    unlockQuest: '蟲鳴之友',
    unlockSummary: '蒼天戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '寵物'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'moogles',
    name: '莫古力族',
    category: 'allied-societies',
    expansion: 'hw',
    patch: '3.3',
    supportRoles: ['crafting'],
    location: '翻雲霧海',
    unlockQuest: '一封寄往雲上的信',
    unlockSummary: '蒼天製作部落，適合 DoH 練等與素材週轉。',
    rewardSummary: ['製作經驗', '聲望', '坐騎', '樂譜'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'kojin',
    name: '甲人族',
    category: 'allied-societies',
    expansion: 'sb',
    patch: '4.0',
    supportRoles: ['combat'],
    location: '紅玉海',
    unlockQuest: '深海之友',
    unlockSummary: '紅蓮戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '家具'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'ananta',
    name: '阿難陀族',
    category: 'allied-societies',
    expansion: 'sb',
    patch: '4.0',
    supportRoles: ['combat'],
    location: '基拉巴尼亞邊區',
    unlockQuest: '蛇女的願望',
    unlockSummary: '紅蓮戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '表情'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'namazu',
    name: '鯰魚精族',
    category: 'allied-societies',
    expansion: 'sb',
    patch: '4.3',
    supportRoles: ['crafting', 'gathering'],
    location: '延夏',
    unlockQuest: '滑不溜丟的委託',
    unlockSummary: '紅蓮生產部落，對 DoH / DoL 都有價值。',
    rewardSummary: ['製作與採集經驗', '聲望', '坐騎'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'pixies',
    name: '妖精族',
    category: 'allied-societies',
    expansion: 'shb',
    patch: '5.1',
    supportRoles: ['combat'],
    location: '伊爾美格',
    unlockQuest: '小妖精的約定',
    unlockSummary: '漆黑戰鬥部落任務。',
    rewardSummary: ['聲望', '坐騎', '表情'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'qitari',
    name: '奇塔利族',
    category: 'allied-societies',
    expansion: 'shb',
    patch: '5.2',
    supportRoles: ['gathering'],
    location: '拉凱提卡大森林',
    unlockQuest: '回憶中的文物',
    unlockSummary: '漆黑採集部落。',
    rewardSummary: ['採集經驗', '聲望', '坐騎'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'dwarves',
    name: '矮人族',
    category: 'allied-societies',
    expansion: 'shb',
    patch: '5.3',
    supportRoles: ['crafting'],
    location: '寇爾西亞島',
    unlockQuest: '酒與鐵鎚',
    unlockSummary: '漆黑製作部落。',
    rewardSummary: ['製作經驗', '聲望', '坐騎'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'arkasodara',
    name: '阿卡薩多拉族',
    category: 'allied-societies',
    expansion: 'ew',
    patch: '6.15',
    supportRoles: ['combat'],
    location: '薩維奈島',
    unlockQuest: '大象們的修行',
    unlockSummary: '曉月戰鬥部落。',
    rewardSummary: ['聲望', '坐騎', '表情'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'omicrons',
    name: '歐米茄族',
    category: 'allied-societies',
    expansion: 'ew',
    patch: '6.25',
    supportRoles: ['gathering'],
    location: '天外天垓',
    unlockQuest: '宇宙中的採集委託',
    unlockSummary: '曉月採集部落。',
    rewardSummary: ['採集經驗', '聲望', '坐騎'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'loporrits',
    name: '月兔族',
    category: 'allied-societies',
    expansion: 'ew',
    patch: '6.35',
    supportRoles: ['crafting'],
    location: '迷津',
    unlockQuest: '月面工坊大作戰',
    unlockSummary: '曉月製作部落。',
    rewardSummary: ['製作經驗', '聲望', '坐騎', '樂譜'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'pelupelu',
    name: '佩魯佩魯族',
    category: 'allied-societies',
    expansion: 'dt',
    patch: '7.15',
    supportRoles: ['combat'],
    location: '圖拉爾',
    unlockQuest: '商旅同盟',
    unlockSummary: '黃金初期的戰鬥部落。',
    rewardSummary: ['聲望', '坐騎', '表情'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'mamool-ja',
    name: '瑪姆加族',
    category: 'allied-societies',
    expansion: 'dt',
    patch: '7.25',
    supportRoles: ['gathering'],
    location: '圖拉爾',
    unlockQuest: '林地的採集者',
    unlockSummary: '黃金採集部落。',
    rewardSummary: ['採集經驗', '聲望', '坐騎'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
  {
    id: 'yok-huy',
    name: '尤克胡伊族',
    category: 'allied-societies',
    expansion: 'dt',
    patch: '7.35',
    supportRoles: ['crafting'],
    location: '圖拉爾',
    unlockQuest: '石匠與工匠',
    unlockSummary: '截至 2026-03-05 的最新黃金製作部落。',
    rewardSummary: ['製作經驗', '聲望', '坐騎'],
    sourceUrl: 'https://ffxiv.consolegameswiki.com/wiki/Allied_Society_Quests',
  },
]

export function getCollectionEntryById(entryId: string): CollectionEntry | undefined {
  return collectionEntries.find((entry) => entry.id === entryId)
}
